sns-sdks/python-facebook

pyfacebook/api.py
pyfacebook/utils/constant.py

the field tagged_time only worked on tagged resource.

fix(posts): remove effect field for posts

---

CHANGELOG.md
README-zh.rst
README.rst
pyfacebook/__version__.py
pyfacebook/api/facebook.py
pyfacebook/models/comment.py
tests/facebook/apis/test_comments.py
tests/facebook/apis/test_page.py

Feat new for v5.0

---

Makefile
docs/extended_api_methods.rst
examples/extend_api.py

Add example for extend this library

Feat examples

---

pyfacebook/ratelimit.py

fix(RateLimitData): different than the graph api responses

---

examples/extend_api.py

fix(example): :bug: fix example for extend api

---

pyfacebook/api/instagram.py
testdata/instagram/apidata/medias/tags_medias.json
testdata/instagram/apidata/medias/tags_medias_p1.json
testdata/instagram/apidata/medias/tags_medias_p2.json
tests/instagram/pro_apis/test_media.py

feat(tags): :sparkles: add new api for get ig tags edias

---

README.rst

Ask requested in https://github.com/sns-sdks/python-facebook/issues/67 I have made some changes I noted some days ago. I hope they are acceptable.

Made some grammatical improvements to Readme.rst

---

pyfacebook/utils/param_validation.py
tests/utils/test_param_validation.py

fix(params): :bug: fix when check string fields may lost some fields

---

pyproject.toml

chore(requirement): :arrow_up: update responses for new

---

pyfacebook/models/ig_pro_models.py

fix(insights): :bug: fix instagram insights for different return type

---

pyfacebook/api/base.py
tests/test_base_api.py

fix(version): :bug: fix regex for version

---

pyfacebook/api/instagram.py
pyfacebook/models/ig_pro_models.py
pyfacebook/utils/constant.py
pyproject.toml

fix(story): :sparkles: update ig stories

---

pyfacebook/api/base.py
pyfacebook/api/instagram.py
pyfacebook/api/instagram_basic.py
tests/instagram/pro_apis/test_media.py

Add since~until to ig media api
Remove pro api media method since_time and until_time param
ISSUES CLOSED: #111,#112

feat(V11): :sparkles: Update API Version to V11.0

---

pyfacebook/api/instagram_business/resource/user.py
testdata/instagram/apidata/users/live_medias.json
tests/instagram_business/test_user.py

feat(api): :sparkles: add api get instagram business live media

---

pyfacebook/api/graph.py
tests/test_graph.py

feat(initial): :sparkles: Supoort more url set in initial

---

pyfacebook/models/post.py

fix(message): :bug: fix model if post not have message

---

pyfacebook/api/graph.py
tests/test_graph.py

add v16,v17 and support set old version
CLOSED #222

feat: 🎸 version

---

pyfacebook/api/facebook/common_edges/__init__.py
pyfacebook/api/facebook/common_edges/likes.py
pyfacebook/api/facebook/resource/album.py
pyfacebook/api/facebook/resource/comment.py
pyfacebook/api/facebook/resource/live_video.py
pyfacebook/api/facebook/resource/page.py
pyfacebook/api/facebook/resource/photo.py
pyfacebook/api/facebook/resource/post.py
pyfacebook/api/facebook/resource/user.py
pyfacebook/api/facebook/resource/video.py
pyfacebook/api/graph.py
pyfacebook/models/extensions.py
pyfacebook/models/image.py
pyfacebook/models/user.py
pyfacebook/utils/constant.py
testdata/facebook/apidata/likes/likes_resp.json
tests/facebook/edges/test_likes.py

add likes edge for resouces
#214

feat: 🎸 likes

---

pyfacebook/api/facebook/resource/comment.py
pyfacebook/api/graph.py
testdata/facebook/apidata/comments/create_resp.json
tests/facebook/test_comment.py

Feat comments

---

pyfacebook/ratelimit.py
tests/test_ratelimit.py

fix ratelimit error with new fields
✅ Closes: #240

fix: 🐛 ratelimit
